name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        fetch-depth: '0'
        submodules: true
        
    - name: make sure gh-pages branch is there
      run: |
        git checkout gh-pages
        git checkout master
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: delete .git dirs in submodules
      run: |
        python clear_git.py

    - name: Compile Pelican blog
      run: |
        pelican content -o output -s publishconf.py
        
    - name: Copy output to gh-pages branch and push
      run: |
        ghp-import output/ -b gh-pages -p -c www.diogoaos.com
